const Input = require('readline-sync')
let idade = Input.question()
let nota = Input.question()
let letra = Input.question()
let nome = Input.question()
console.log(idade)
console.log(nota)
console.log(letra)
console.log(nome)