const Input = require('readline-sync')
let nome = Input.question()
let idade = Input.question()
let cidade = Input.question()
console.log("Ola! Meu nome é "+ nome, "tenho "+idade, " anos e sou de " + cidade)